### ISSUE TITLE
App Doesn't Work

### ISSUE THREAD

**Issue by daniellytle** [mcopley08/troll-me#1]
I paid the trolls toll but something's jacked

**Comment by mcopley08** [comment]
Is it not letting you log in at all? I've just submitted the application to Facebook and have to hear back from them, so as of right now they will only allow my account to use the application.

p.s. - hi dan <3

**Comment by daniellytle** [comment]
haha sorry dude, bad bug report. I log in with facebook the screen moves down. I see a loading spinner and part of the contribute page and it just hangs there.

ps - hey mike :100:

**Comment by mcopley08** [comment]
ahhh damn :( lol, ill check this out. time to spam the console with status messages.

does the loading spinner never go away? or is it a UI issue where the scroller gets caught up in a certain section?

**Comment by daniellytle** [comment]
haha yeah dude go gettem! and yeah it just chills there in the right position I think.

**Comment by mcopley08** [comment]
Okay, I looked into it and the reason it just stays like that is because it is trying to make an API call to retrieve data that the app doesn't currently allow - it only has access to a user's public profile and it is asking for quite a bit more than that, so when it tries to manipulate it, a JavaScript error is thrown so the suggestions never get presented to the user.

For now, I'm going to wait it out until Facebook (hopefully) approves the other data it is requesting, because it does work locally for me - anyone on the developer account will be able to try it out without having Facebook approve it.

If you wanted to mess around with it a bit, I've given you permission in the Facebook Developer console. So it should work now for you... hopefully...

**Comment by daniellytle** [comment]
Sweet man! Yeah I'll let you know what happens. If this is something you'd wanna continue working on I'd love to contribute.

**Comment by mcopley08** [comment]
hey dan <3 im going to close this for now because i dont want you to have the stress of this repo issue on your mind.
